### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference on OpenBSD

### ISSUE THREAD

**Issue by huhndev** [charmbracelet/mods#186]
Moin!

I just build `mods` on OpenBSD -current and got the following panic when trying to run `mods`. Reproducable with v1.0.0, v1.1.0 and the latest commits from main. v0.2.0 runs fine.

If I can provide any further information, please let me know.

```
$ mods
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf8db5c]

goroutine 1 [running]:
modernc.org/libc.(*TLS).setErrno(0x17533e0?, {0x245660?, 0x58f260?})
        /home/jhuhn/go/pkg/mod/modernc.org/libc@v1.24.1/etc.go:189 +0xdc
modernc.org/libc.Xmalloc(0x2decc0?, 0x598868?)
        /home/jhuhn/go/pkg/mod/modernc.org/libc@v1.24.1/mem.go:34 +0xc5
modernc.org/libc.init()
        /home/jhuhn/go/pkg/mod/modernc.org/libc@v1.24.1/libc_openbsd.go:49 +0x1db
```

**Comment by caarlos0** [comment]
seems to be an issue with modernc.org/libc: https://gitlab.com/cznic/libc/-/blob/v1.24.1/libc_openbsd.go?ref_type=tags#L49

I'll update modernc.org/sqlite (which depends on modernc.org/libc) and see if it changes anything, but by the looks of it it doesn't 🤔

**Comment by huhndev** [comment]
```
$ go build
go: downloading modernc.org/sqlite v1.28.0
go: downloading modernc.org/libc v1.29.0
go: downloading modernc.org/mathutil v1.6.0
go: downloading modernc.org/memory v1.7.2
# github.com/charmbracelet/mods
./main.go:373:11: undefined: newUserError

$ go install github.com/charmbracelet/mods@libc
go: downloading github.com/charmbracelet/mods v1.1.1-0.20240110012018-c44309a87942
# github.com/charmbracelet/mods
/home/jhuhn/go/pkg/mod/github.com/charmbracelet/mods@v1.1.1-0.20240110012018-c44309a87942/main.go:373:11: undefined: newUserError
```

Hmm, now it doesn't even build.

**Comment by caarlos0** [comment]
fixed

**Comment by huhndev** [comment]
Seems to be related to https://gitlab.com/cznic/libc/-/issues/34

**Comment by cloudkucooland** [comment]
I've reworked the necessary logic for modernc/libc on openbsd, It should also fix modernc/mysql. Please update dependencies and try now.

Discussion at https://gitlab.com/cznic/libc/-/issues/34

**Comment by huhndev** [comment]
Moin!

 `mods` builds and runs fine with your latest fix on OpenBSD -current. 

Unfortunately, I no longer have an OpenAI API key, which is why I can only test up to the error message that I am missing the API key.

Thanks, @cloudkucooland and @caarlos0!

**Comment by caarlos0** [comment]
@huhndev thank you for trying it! 🙏
